// <auto-generated />
using System;
using Fox.Whs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fox.Whs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030093701_Hinata")]
    partial class Hinata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd_LHC.SapModels.ProductionShift", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("@CAXS", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Fox.Whs.Models.BlowingProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductionShift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftLeaderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBlowingLoss")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TotalBlowingOutput")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TotalReservedOutput")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TotalRewindingOutput")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftLeaderId");

                    b.ToTable("Fox_BlowingProcesses");
                });

            modelBuilder.Entity("Fox.Whs.Models.BlowingProcessLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlowingMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlowingProcessId")
                        .HasColumnType("int");

                    b.Property<string>("BlowingSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BlowingStageInventory")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DelayReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ElectricalIssue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExcessPO")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HumanErrorKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HumanErrorReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InnerCoating")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MachineErrorKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MachineErrorReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaterialLossKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaterialLossReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtherErrorKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OtherErrorReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionBatch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantityRolls")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReservedWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RewindOrSplitWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SemiProductWarehouseConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SemiProductWidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StopDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("StopReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thickness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TrimmedEdge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("WeighingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WidthChange")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlowingProcessId");

                    b.HasIndex("CardCode");

                    b.HasIndex("WorkerId");

                    b.ToTable("Fox_BlowingProcessLines");
                });

            modelBuilder.Entity("Fox.Whs.SapModels.Blower", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Code");

                    b.ToTable("@MAYTHOI", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Fox.Whs.SapModels.BusinessPartner", b =>
                {
                    b.Property<string>("CardCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CardCode");

                    b.Property<string>("CardName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CardName");

                    b.HasKey("CardCode");

                    b.ToTable("OCRD", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Fox.Whs.SapModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("empID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastName");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("middleName");

                    b.HasKey("Id");

                    b.ToTable("OHEM", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Fox.Whs.SapModels.Item", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ItemCode");

                    b.Property<string>("FrgnName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FrgnName");

                    b.Property<short?>("ItemGrpCode")
                        .HasColumnType("smallint")
                        .HasColumnName("ItmsGrpCod");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ItemName");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("U_CHL");

                    b.Property<string>("SemiProductWidth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("U_KMBTP");

                    b.Property<string>("Thickness")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("U_DD1L");

                    b.HasKey("ItemCode");

                    b.ToTable("OITM", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Fox.Whs.SapModels.ProductionOrder", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DocEntry");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocEntry"));

                    b.Property<string>("CardCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CardCode");

                    b.Property<string>("DateOfNeedBlowing")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("U_THOINCH");

                    b.Property<int>("DocNum")
                        .HasColumnType("int")
                        .HasColumnName("DocNum");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ItemCode");

                    b.Property<string>("ProductionBatch")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("U_LOSX");

                    b.HasKey("DocEntry");

                    b.HasIndex("CardCode");

                    b.HasIndex("ItemCode");

                    b.ToTable("OWOR", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Fox.Whs.SapModels.User", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("USERID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("U_NAME");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USER_CODE");

                    b.HasKey("Id");

                    b.ToTable("OUSR", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Fox.Whs.SapModels.UserGroup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("GroupId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GroupName");

                    b.HasKey("Id");

                    b.ToTable("OUGR", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Fox.Whs.SapModels.UserGroupAssignment", b =>
                {
                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("UserId");

                    b.Property<short>("GroupId")
                        .HasColumnType("smallint")
                        .HasColumnName("GroupId");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("USR7", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Fox.Whs.Models.BlowingProcess", b =>
                {
                    b.HasOne("Fox.Whs.SapModels.Employee", "ShiftLeader")
                        .WithMany()
                        .HasForeignKey("ShiftLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftLeader");
                });

            modelBuilder.Entity("Fox.Whs.Models.BlowingProcessLine", b =>
                {
                    b.HasOne("Fox.Whs.Models.BlowingProcess", "BlowingProcess")
                        .WithMany("Lines")
                        .HasForeignKey("BlowingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fox.Whs.SapModels.BusinessPartner", "BusinessPartner")
                        .WithMany()
                        .HasForeignKey("CardCode");

                    b.HasOne("Fox.Whs.SapModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("WorkerId");

                    b.Navigation("BlowingProcess");

                    b.Navigation("BusinessPartner");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fox.Whs.SapModels.ProductionOrder", b =>
                {
                    b.HasOne("Fox.Whs.SapModels.BusinessPartner", "BusinessPartnerDetail")
                        .WithMany()
                        .HasForeignKey("CardCode");

                    b.HasOne("Fox.Whs.SapModels.Item", "ItemDetail")
                        .WithMany()
                        .HasForeignKey("ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPartnerDetail");

                    b.Navigation("ItemDetail");
                });

            modelBuilder.Entity("Fox.Whs.SapModels.UserGroupAssignment", b =>
                {
                    b.HasOne("Fox.Whs.SapModels.UserGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fox.Whs.SapModels.User", null)
                        .WithMany("GroupAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Fox.Whs.Models.BlowingProcess", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Fox.Whs.SapModels.User", b =>
                {
                    b.Navigation("GroupAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
